"use client";

import { useFirestoreCollection } from "@/hooks/use-firestore";
import { Report } from "@/types/schema";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Eye, Edit, Plus } from "lucide-react";
import { useRouter } from "next/navigation";

export default function ReportsPage() {
  const router = useRouter();
  const { data: reports, loading } = useFirestoreCollection<Report>("reports", "createdAt", "desc");

  return (
    <div className="space-y-8 p-8 pt-6">
       <div className="flex items-center justify-between">
          <div>
             <h1 className="text-3xl font-bold tracking-tight text-primary">Reports & Clinical Documents</h1>
             <p className="text-muted-foreground">Manage generated assessments and consultation summaries.</p>
          </div>
          <Button>
              <Plus className="mr-2 h-4 w-4" /> Create Manual Report
          </Button>
       </div>

       <Card>
           <CardHeader>
               <CardTitle>Recent Reports</CardTitle>
               <CardDescription>All clinical documentation generated by you or the AI Co-Pilot.</CardDescription>
           </CardHeader>
           <CardContent>
               <Table>
                   <TableHeader>
                       <TableRow>
                           <TableHead>Title</TableHead>
                           <TableHead>Type</TableHead>
                           <TableHead>Status</TableHead>
                           <TableHead>Date</TableHead>
                           <TableHead className="text-right">Actions</TableHead>
                       </TableRow>
                   </TableHeader>
                   <TableBody>
                       {reports.map((report) => (
                           <TableRow key={report.id}>
                               <TableCell className="font-medium">
                                   <div className="flex items-center gap-2">
                                       <FileText className="h-4 w-4 text-blue-500" />
                                       {report.title || "Untitled Report"}
                                   </div>
                               </TableCell>
                               <TableCell>Consultation Summary</TableCell>
                               <TableCell>
                                   <Badge variant={report.status === 'final' ? 'default' : 'outline'}>
                                       {report.status}
                                   </Badge>
                               </TableCell>
                               <TableCell>{new Date(report.createdAt).toLocaleDateString()}</TableCell>
                               <TableCell className="text-right space-x-2">
                                   <Button variant="ghost" size="icon" onClick={() => router.push(`/dashboard/reports/editor/${report.id}`)}>
                                       <Edit className="h-4 w-4" />
                                   </Button>
                                   <Button variant="ghost" size="icon">
                                       <Download className="h-4 w-4" />
                                   </Button>
                               </TableCell>
                           </TableRow>
                       ))}
                       {!loading && reports.length === 0 && (
                           <TableRow>
                               <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                                   No reports found.
                               </TableCell>
                           </TableRow>
                       )}
                   </TableBody>
               </Table>
           </CardContent>
       </Card>
    </div>
  );
}
