"use client";

import { useFirestoreCollection } from "@/hooks/use-firestore";
import { InterventionPlan, AssessmentResult } from "@/types/schema";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Printer, Loader2, FileText, Download } from "lucide-react";
import { useState } from "react";
import { formatCitation } from "@/ai/knowledge/citationFormat";

export default function ReportBuilderPage() {
    // In real app, select specific case/assessment. Here we list recent assessments to pick from.
    const { data: results, loading } = useFirestoreCollection<AssessmentResult>("assessment_results", "completedAt", "desc");
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const [generating, setGenerating] = useState(false);
    const [reportHtml, setReportHtml] = useState("");

    const selectedResult = results.find(r => r.id === selectedId);

    const generateReport = async () => {
        if (!selectedResult) return;
        setGenerating(true);
        // Simulate Report Generation
        await new Promise(r => setTimeout(r, 1000));
        
        // Mock Content Construction
        const html = `
            <div class="p-8 max-w-2xl mx-auto border bg-white shadow-sm my-8">
                <h1 class="text-3xl font-bold mb-4">Confidential Psychological Report</h1>
                <p class="text-sm text-gray-500 mb-8">Date: ${new Date().toLocaleDateString()} | Student ID: ${selectedResult.studentId}</p>
                
                <h2 class="text-xl font-bold border-b pb-2 mb-4">Assessment Findings</h2>
                <div class="prose text-sm whitespace-pre-wrap mb-8">
                    ${selectedResult.aiAnalysis || "No summary available."}
                </div>

                <h2 class="text-xl font-bold border-b pb-2 mb-4">Evidence & References</h2>
                <div class="text-xs text-gray-600 mb-8">
                    <p>The following guidelines were consulted:</p>
                    <ul class="list-disc pl-4 mt-2">
                        <li>${formatCitation("NICE Guideline NG87", "Attention deficit hyperactivity disorder: diagnosis and management", "2018")}</li>
                        <li>${formatCitation("MindKindler Knowledge Base", "Internal policy on safeguarding procedures")}</li>
                    </ul>
                </div>

                <h2 class="text-xl font-bold border-b pb-2 mb-4">Recommended Interventions</h2>
                <div class="space-y-4">
                    <div class="bg-gray-50 p-4 rounded">
                        <h4 class="font-bold">1. Classroom Accommodations</h4>
                        <p class="text-sm">Implement preferential seating and broken-down instructions.</p>
                    </div>
                    <div class="bg-gray-50 p-4 rounded">
                        <h4 class="font-bold">2. Parental Support</h4>
                        <p class="text-sm">Refer to 'Early Years' workshop series.</p>
                    </div>
                </div>

                <div class="mt-12 pt-4 border-t text-center text-xs text-gray-400">
                    Generated by MindKindler AI • Verified by EPP
                </div>
            </div>
        `;
        setReportHtml(html);
        setGenerating(false);
    };

    const handlePrint = () => {
        const printWindow = window.open('', '_blank');
        printWindow?.document.write(`
            <html>
                <head><title>Report</title><script src="https://cdn.tailwindcss.com"></script></head>
                <body>${reportHtml}</body>
            </html>
        `);
        printWindow?.document.close();
        printWindow?.print();
    };

    return (
        <div className="p-8 space-y-8">
            <div>
                <h1 className="text-3xl font-bold">Report Builder</h1>
                <p className="text-muted-foreground">Compile assessments, evidence, and plans into a formal document.</p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <Card>
                    <CardHeader><CardTitle>Select Source</CardTitle></CardHeader>
                    <CardContent>
                        {loading && <Loader2 className="animate-spin" />}
                        <div className="space-y-2">
                            {results.slice(0, 5).map(res => (
                                <div 
                                    key={res.id} 
                                    className={`p-3 border rounded cursor-pointer hover:bg-slate-50 ${selectedId === res.id ? 'border-primary bg-primary/5' : ''}`}
                                    onClick={() => setSelectedId(res.id)}
                                >
                                    <div className="font-medium text-sm">Assessment {res.id.substring(0, 6)}</div>
                                    <div className="text-xs text-muted-foreground">{new Date(res.completedAt || "").toLocaleDateString()}</div>
                                </div>
                            ))}
                        </div>
                    </CardContent>
                </Card>

                <div className="lg:col-span-2">
                    {selectedId && !reportHtml && (
                        <div className="h-full flex items-center justify-center border-2 border-dashed rounded-lg p-12">
                            <Button onClick={generateReport} disabled={generating}>
                                {generating && <Loader2 className="mr-2 h-4 w-4 animate-spin"/>} Generate Report Draft
                            </Button>
                        </div>
                    )}

                    {reportHtml && (
                        <div className="space-y-4">
                            <div className="flex justify-end gap-2">
                                <Button variant="outline" onClick={() => setReportHtml("")}>Back</Button>
                                <Button onClick={handlePrint}><Printer className="mr-2 h-4 w-4"/> Print / PDF</Button>
                            </div>
                            <div className="border shadow-lg" dangerouslySetInnerHTML={{ __html: reportHtml }} />
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
