import { differenceInYears, parseISO } from 'date-fns';

/**
 * Represents a specific clinical activity recommended for a case.
 */
export interface EngagementActivity {
    id: string;
    title: string;
    type: 'observation' | 'interview' | 'assessment' | 'consultation';
    /** Is this strictly required by protocol or just recommended? */
    required: boolean;
    /** Explanation for why this was chosen (e.g. "Child is non-verbal") */
    rationale: string;
    /** Appropriate setting (e.g. "Classroom", "Home", "Clinic") */
    recommendedSetting: string;
}

/**
 * The complete clinical plan generated by the engine.
 */
export interface EngagementPlan {
    strategyName: string; // e.g., "Early Years Play-Based" or "Standard Secondary Assessment"
    activities: EngagementActivity[];
    requiredEvidence: string[]; // List of report types needed (e.g., "Social Care Report")
    safeguardingNote?: string;
}

/**
 * Input parameters for the Engagement Engine.
 */
export interface EngagementContext {
    dob: string; // ISO Date
    isNonVerbal: boolean;
    hasSocialWorker: boolean;
    // Potentially extend with: historyOfTrauma, eal (English as Additional Language), etc.
}

/**
 * Clinical Logic Engine
 * Analyzes case metadata to recommend the most appropriate engagement strategy.
 * 
 * Clinical Heuristics:
 * 1. Early Years (<6): Focus on play-based observation and caregiver interviews. Direct testing is unreliable.
 * 2. Non-Verbal: Standard interview protocols fail. Use observation and non-verbal reasoning tools.
 * 3. Adolescents (>11): Agency is key. Direct interviews and "Card Sort" activities to elicit their views (Section A).
 * 4. Social Care Involvement: If a Social Worker is present, we MUST triage with them to understand safeguarding context before visiting.
 * 
 * @param context - The child's demographic and risk profile.
 * @returns A structured EngagementPlan.
 */
export function generateEngagementPlan(context: EngagementContext): EngagementPlan {
    const age = differenceInYears(new Date(), parseISO(context.dob));
    
    const plan: EngagementPlan = {
        strategyName: 'Standard Assessment',
        activities: [],
        requiredEvidence: ['School Information Form', 'Parent Contribution (Section A)'],
    };

    // --- Rule 1: Early Years Logic (< 6 years old) OR Non-Verbal ---
    if (age < 6 || context.isNonVerbal) {
        plan.strategyName = age < 6 ? 'Early Years Pathway' : 'Complex Needs / Non-Verbal Pathway';
        
        plan.activities.push({
            id: 'obs-play',
            title: 'Play-Based Observation',
            type: 'observation',
            required: true,
            rationale: context.isNonVerbal 
                ? 'Child is non-verbal; direct interview is not appropriate. Observation of communication intent is key.' 
                : 'Developmental stage requires play-based assessment rather than formal testing.',
            recommendedSetting: 'Natural Setting (Home or Nursery)'
        });

        plan.activities.push({
            id: 'int-caregiver',
            title: 'Parent/Carer Detailed History',
            type: 'interview',
            required: true,
            rationale: 'Primary source of developmental history and "Voice of the Child" proxy.',
            recommendedSetting: 'Private Room (Child not present)'
        });
        
        // Explicitly disable direct interview if it was default
        // (In this logic, we build up, so we just don't add it)
    } 
    
    // --- Rule 2: Secondary / Adolescent Logic (> 11 years old) AND Verbal ---
    else if (age > 11 && !context.isNonVerbal) {
        plan.strategyName = 'Secondary / Transition Pathway';

        plan.activities.push({
            id: 'int-student',
            title: 'Direct Pupil Interview',
            type: 'interview',
            required: true,
            rationale: 'Student is of age to express their own aspirations and needs directly.',
            recommendedSetting: 'Quiet Room in School'
        });

        plan.activities.push({
            id: 'act-cardsort',
            title: 'Ideal School / Card Sort Activity',
            type: 'assessment',
            required: false, // Recommended tool
            rationale: 'Projective technique to help student articulate school preferences and anxieties.',
            recommendedSetting: '1:1 Session'
        });
    }

    // --- Default / Middle Years Logic (6-11 Verbal) ---
    else {
        // Fallback for standard primary age
        plan.activities.push({
            id: 'obs-class',
            title: 'Classroom Observation',
            type: 'observation',
            required: true,
            rationale: 'Observe learning behavior and social interaction in standard environment.',
            recommendedSetting: 'Classroom'
        });

        plan.activities.push({
            id: 'int-student-short',
            title: 'Pupil Conferencing',
            type: 'interview',
            required: true,
            rationale: 'Short, structured interview to ascertain views on school.',
            recommendedSetting: 'Quiet Area'
        });
    }

    // --- Rule 3: Social Care Overlay ---
    if (context.hasSocialWorker) {
        plan.requiredEvidence.push('Social Care Statutory Advice');
        
        plan.activities.push({
            id: 'cons-sw',
            title: 'Social Worker Consultation',
            type: 'consultation',
            required: true,
            rationale: 'Safeguarding context must be established. Child may be Looked After (LAC) or Child in Need (CIN).',
            recommendedSetting: 'Telephone / Teams'
        });
        
        plan.safeguardingNote = "High Priority: Contact Social Worker before scheduling home visits.";
    }

    return plan;
}
