// src/types/analytics.ts

export type AlertType = 'school_cluster' | 'community_cluster' | 'sibling_risk';
export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical';

/**
 * A notification generated by "The Guardian" pattern engine.
 * Represents a systemic risk rather than an individual clinical risk.
 */
export interface SystemicAlert {
    id: string;
    
    /** The logic rule that triggered this */
    type: AlertType;
    
    /** The entity associated with the cluster (School ID, Postcode Sector, or Sibling Case ID) */
    targetId: string;
    targetName?: string; // e.g. "St. Mary's Primary" or "LS2"
    
    severity: AlertSeverity;
    
    /** Human-readable explanation */
    description: string; // e.g., "3 students from School X reported Self-Harm..."
    
    /** When was this pattern detected? */
    detectedAt: string; // ISO Date
    
    /** The individual cases that form this pattern */
    relatedCaseIds: string[];
    
    /** Has this been acknowledged by an admin? */
    status: 'new' | 'acknowledged' | 'investigating' | 'resolved';
}

/**
 * Aggregated statistics for the District Command Center.
 */
export interface DistrictReport {
    generatedAt: string;
    
    /** Total active caseload */
    totalActiveCases: number;
    
    /** Count of cases per primary need (e.g., { 'Autism': 45, 'SEMH': 30 }) */
    topNeeds: Record<string, number>;
    
    /** Number of cases predicted to breach the 20-week statutory deadline */
    breachProjections: number;
    
    /** List of currently active systemic alerts */
    activeAlerts: SystemicAlert[];
}
