// src/types/schema.ts

// ... (Existing Roles)
// NOTE: We permit both "EPP" and "EducationalPsychologist" as strings here to support legacy/variant roles, 
// but code should ideally normalize.
export type Role = 
    'SuperAdmin' | 
    'TenantAdmin' | 
    'EPP' | 
    'EducationalPsychologist' | 
    'Assistant' | 
    'TrustedAssistant' | 
    'SchoolAdmin' | 
    'ParentUser' | 
    'GovAnalyst';

// ... (Provenance & Trust)
export interface ProvenanceMetadata {
    source: 'manual' | 'ocr' | 'lms' | 'parent_portal' | 'migration';
    sourceId?: string;
    confidence?: number;
    verified: boolean;
    verifiedBy?: string;
    verifiedAt?: string;
    autoGenerated?: boolean;
}

export type ProvenanceField<T> = {
    value: T;
    metadata: ProvenanceMetadata;
}

export interface VerificationTask {
    id: string;
    studentId: string;
    fieldPath: string;
    description: string;
    status: 'pending' | 'verified' | 'rejected' | 'skipped';
    assignedTo?: string;
    dueDate?: string;
    evidenceRef?: string;
    createdAt: string;
    resolvedAt?: string;
    resolvedBy?: string;
}

// ... (Student 360 Core)
export interface ParentRecord {
    id: string;
    tenantId: string;
    firstName: string;
    lastName: string;
    relationshipType: 'Mother' | 'Father' | 'Guardian' | 'Foster Carer' | 'Step-Parent' | 'Grandparent' | 'Other';
    email?: string;
    phone?: string;
    address?: string;
    hasParentalResponsibility: boolean;
    isPrimaryContact: boolean;
    isEmergencyContact: boolean;
    canPickUp: boolean;
    occupation?: string;
    employer?: string;
    languages: string[];
    communicationPreferences?: {
        email: boolean;
        sms: boolean;
        phone: boolean;
        preferredTime?: string;
    };
    verificationStatus: 'unverified' | 'verified_id' | 'verified_in_person';
    metadata?: ProvenanceMetadata;
}

export interface FosterPlacement {
    id: string;
    carerName: string;
    agencyName: string;
    startDate: string;
    endDate?: string;
    reasonForMove?: string;
    legalStatus: string;
    socialWorkerName?: string;
    contactInfo?: string;
    metadata: ProvenanceMetadata;
}

export interface DisciplineIncident {
    id: string;
    date: string;
    type: string;
    description: string;
    outcome: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    involvedParties?: string[];
    reportedBy: string;
    isPoliceInvolved?: boolean;
    isSafeguarding?: boolean;
    metadata: ProvenanceMetadata;
}

export interface HealthRecord {
    gpName?: string;
    gpPractice?: string;
    nhsNumber?: string;
    allergies: ProvenanceField<string[]>;
    conditions: ProvenanceField<string[]>;
    medications: ProvenanceField<string[]>;
    immunizations?: ProvenanceField<string[]>;
    dietaryNeeds?: string;
    emergencyPlan?: string;
}

export interface ConsentRecord {
    id: string;
    studentId: string;
    parentId?: string;
    category: 'education_share' | 'health_share' | 'media_recording' | 'research' | 'marketing' | 'third_party';
    status: 'granted' | 'denied' | 'revoked' | 'expired';
    grantedAt: string;
    expiresAt?: string;
    evidenceFileId?: string;
    notes?: string;
}

export interface StudentRecord {
    id: string;
    tenantId: string;
    schoolId?: string; // Links student to a School Organization
    
    identity: {
        firstName: ProvenanceField<string>;
        lastName: ProvenanceField<string>;
        middleName?: ProvenanceField<string>;
        preferredName?: string;
        dateOfBirth: ProvenanceField<string>;
        gender: ProvenanceField<string>;
        nationalId?: ProvenanceField<string>;
        upi?: ProvenanceField<string>;
        photoUrl?: string;
    };

    education: {
        currentSchoolId?: ProvenanceField<string>;
        enrollmentDate?: ProvenanceField<string>;
        yearGroup?: ProvenanceField<string>;
        formGroup?: string;
        senStatus?: ProvenanceField<string>;
        fsmStatus?: ProvenanceField<boolean>;
        ealStatus?: ProvenanceField<boolean>;
        attendancePercentage?: ProvenanceField<number>;
    };

    family: {
        parents: ParentRecord[];
        siblings?: { name: string; dob?: string; school?: string }[];
        languageHome?: string;
    };

    health: HealthRecord;

    careHistory?: {
        isLookedAfter: boolean;
        socialWorker?: { name: string; email: string; phone: string };
        placements: FosterPlacement[];
    };

    discipline?: DisciplineIncident[];

    // Extension field for Country OS Modular Architecture
    extensions?: Record<string, any>; 

    meta: {
        createdAt: string;
        createdBy: string;
        updatedAt: string;
        updatedBy: string;
        trustScore: number;
        completenessScore: number;
        privacyLevel: 'standard' | 'high' | 'restricted';
    };
}

// ... (Legacy & Support Types)
export interface AiFeedback {
    id: string;
    tenantId: string;
    userId: string;
    traceId: string;
    feature: string;
    rating: 'positive' | 'negative';
    reason?: 'hallucination' | 'style' | 'missed_fact' | 'unsafe' | 'other';
    comment?: string;
    correctedValue?: string;
    createdAt: string;
}

export interface AssessmentRecommendation {
    templateId: string;
    title: string;
    category: string;
    reasoning: string;
    confidence: 'high' | 'medium' | 'low';
    isAvailable: boolean;
}

export interface Notification {
  id: string;
  tenantId: string;
  recipientUserId: string;
  type: 'info' | 'success' | 'warning' | 'error' | 'action_required';
  category: 'assessment' | 'training' | 'guardian' | 'partner' | 'system';
  title: string;
  message: string;
  link?: string;
  read: boolean;
  createdAt: string;
  metadata?: Record<string, any>;
}

export interface NotificationPreferences {
  userId: string;
  channels: { email: boolean; sms: boolean; push: boolean };
  categories: {
    assessment: boolean;
    training: boolean;
    guardian: boolean;
    partner: boolean;
    system: boolean;
  };
}

export interface UploadedDocument {
  id: string;
  tenantId: string;
  fileName: string;
  status: 'processing' | 'review_required' | 'processed';
  uploadedAt: string;
  uploadedBy: string;
  url: string;
}

export interface AssessmentTemplate {
  id: string;
  tenantId: string;
  title: string;
  description: string;
  category?: string;
  questions: any[];
  createdAt: string;
  updatedAt: string;
  status: 'draft' | 'published';
  tags: string[];
}

export interface AssessmentAssignment {
  id: string;
  tenantId: string;
  templateId: string;
  studentId?: string;
  targetId?: string;
  assignedByUserId: string;
  assignedAt: string;
  dueDate?: string;
  mode?: 'student-async' | 'clinician-live';
  status: 'pending' | 'in_progress' | 'completed' | 'graded';
  responses?: Record<string, any>;
  grade?: number;
  feedback?: string;
}

export interface TenantLocalizationSettings {
  defaultLocale: string;
  supportedLocales: string[];
  allowUserLocaleOverride: boolean;
  updatedAt: string;
  updatedBy: string;
  publishedBy?: string;
}

export interface TenantSettings {
  localization?: TenantLocalizationSettings;
}

export interface TranslationOverrideDoc {
  id?: string;
  locale: string;
  namespace: string;
  entries: Record<string, string>;
  status: 'draft' | 'published';
  updatedAt: string;
  updatedBy: string;
  publishedAt?: string;
  publishedBy?: string;
}

export interface GlossaryDoc {
  id?: string;
  locale: string;
  entries: Record<string, string>;
  status: 'draft' | 'published';
  updatedAt: string;
  updatedBy: string;
  publishedAt?: string;
  publishedBy?: string;
}

export interface ConsultationSession {
  id: string;
  tenantId: string;
  studentId: string;
  date: string;
  notes: string;
  mode: 'person_centered' | 'multi_agency' | 'complex' | 'standard';
  participants: string[];
  audio_url?: string;
  transcript?: {
    startTime: number;
    endTime: number;
    speaker: string;
    text: string;
  }[];
  ai_insights?: {
    timestamp: number;
    text: string;
    type: string;
  }[];
  clinical_observations?: {
    timestamp: number;
    text: string;
  }[];
  linked_assessment_id?: string;
  accessibility?: {
    visual_aids: boolean;
    sign_language_record: boolean;
    live_captions: boolean;
  };
  participant_device_id?: string;
  // UPDATED: Added synthesized and completed statuses
  status?: 'scheduled' | 'in_progress' | 'completed' | 'synthesized' | 'cancelled';
  type?: string; // Added type property
  reportId?: string;
  caseId?: string;
}

export interface ConsultationEvent {
  timestamp: string; // ISO String
  speaker: 'epp' | 'student';
  type: 'audio_transcript' | 'visual_card_selection' | 'ai_insight';
  data?: any; // To hold type-specific payloads like the text or card ID
}

export interface Student {
  id: string;
  tenantId: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender?: string;
  schoolId?: string;
  parentId?: string;
  address?: string;
  needs?: string[];
  alerts?: any[];
  diagnosisCategory?: string[];
  history?: string;
  consent?: {
      shareReports: boolean;
      shareDataForTraining: boolean;
      contactEmail?: string;
  };
}

export type CasePriority = 'Critical' | 'High' | 'Medium' | 'Low';
export type CaseStatus = 'triage' | 'active' | 'waiting' | 'resolved' | 'archived';

export interface Case {
  id: string;
  tenantId: string;
  type: 'student' | 'school' | 'staff';
  subjectId: string;
  title: string;
  description: string;
  status: CaseStatus;
  priority: CasePriority;
  assignedTo?: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  sourceAlertId?: string;
  evidence?: any[];
  tags?: string[];
  slaDueAt?: string;
}

// NEW: Task Management for Assistants
export interface CaseTask {
  id?: string;
  tenantId: string; // Tenant Context
  caseId?: string;  // Linked to a clinical case?
  studentId?: string; // Linked to a student?
  
  title: string;
  description?: string;
  type: 'data_entry' | 'interview' | 'research' | 'observation' | 'report_drafting' | 'general'; // Added general
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'pending' | 'in_progress' | 'review' | 'completed' | 'late';
  
  assignedTo: string; // User ID (Assistant)
  assignedBy: string; // User ID (EPP)
  dueAt: string;
  
  attachments?: {
      name: string;
      url: string;
  }[];
  
  escalationPolicy?: {
      escalateAt: string; // if not done by this time
      escalateTo: string; // User ID (EPP)
  };
  
  createdAt: string;
  completedAt?: string;
}

export interface CaseTimelineEvent {
  id?: string;
  type: 'status_change' | 'note' | 'document' | 'alert_linked' | 'task_completed' | 'assignment_change';
  content: string;
  metadata?: Record<string, any>;
  actorId: string;
  createdAt: string;
}

export interface AssessmentResult {
  id: string;
  studentId: string;
  templateId: string;
  totalScore: number;
  maxScore: number;
  completedAt?: string;
  startedAt?: string;
  category?: string;
  grade?: string;
  responses?: Record<string, any>;
  status?: 'pending' | 'in_progress' | 'completed' | 'graded';
  aiAnalysis?: string;
}

export interface ExternalAcademicRecord {
  id: string;
  studentId: string;
  subject: string;
  grade: string | number;
  term: string;
  date: string;
  sourceSystem: string;
}

export interface AttendanceRecord {
  id: string;
  studentId: string;
  date: string;
  status: 'present' | 'absent' | 'late' | 'excused';
  notes?: string;
}

export interface InterventionPlan {
  id: string;
  tenantId: string;
  studentId: string;
  title: string;
  status: 'active' | 'completed' | 'draft' | 'archived';
  startDate: string;
  endDate?: string;
  goalDescription: string;
  recommendations: Array<{
    title: string;
    description: string;
    assignedTo: string;
    steps?: string[];
    status: 'pending' | 'in_progress' | 'completed';
  }>;
  progressLogs?: Array<{
    at: string;
    note: string;
    progressDelta?: string;
    loggedBy: string;
  }>;
  createdAt: string;
  updatedAt: string;
  baselineScore?: number;
  targetScore?: number;
  currentScore?: number;
}

export interface RecommendationTemplate {
    id: string;
    category: string;
    title: string;
    description: string;
    impactScore: number;
    tags: string[];
}

export type RedactionLevel = 'FULL' | 'PARENT_SAFE' | 'ANONYMIZED';

export interface Citation {
    id: string;
    evidenceId: string;
    sourceType: string;
    label: string;
    trustScore?: number;
    snippet?: string;
    locationIndex?: number;
}

export interface ReportSection {
    id: string;
    title: string;
    content: string;
    lastAiGeneratedAt?: string;
    internalOnly?: boolean;
}

export interface Report {
    id: string;
    tenantId: string;
    studentId: string;
    caseId?: string;
    title: string;
    type: 'consultation' | 'statutory' | 'ehcp_review';
    templateType?: string;
    
    status: 'draft' | 'review' | 'signed' | 'archived';
    version: number;
    
    content: {
        sections: ReportSection[];
    };
    
    citations?: Citation[];
    
    createdBy: string;
    createdAt: any;
    updatedAt: any;
    
    signedBy?: string;
    signedAt?: any;
    signatureHash?: string;
    locked?: boolean;

    aiProvenanceId?: string;
}

export interface ReportVersion {
    id?: string;
    reportId: string;
    versionNumber: number;
    content: { sections: ReportSection[] };
    changeSummary?: string;
    committedBy: string;
    createdAt: any;
    
    type?: 'draft' | 'signed_final';
    signedBy?: string;
    signatureHash?: string;
}

export interface ReportShare {
    id: string;
    reportId: string;
    sharedWithEmail?: string;
    sharedWithUserId?: string;
    redactionLevel: RedactionLevel;
    permissions: 'view' | 'comment' | 'download';
    expiresAt?: string;
    createdAt: string;
    createdBy: string;
    accessKey?: string;
}

export interface ReportExport {
    id: string;
    reportId: string;
    versionId?: string;
    path: string;
    redactionLevel: RedactionLevel;
    requestedBy: string;
    createdAt: any;
}

export interface GuardianFinding {
    id: string;
    tenantId: string;
    ruleId: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    eventType: string;
    subjectType: string;
    subjectId: string;
    message: string;
    remediation?: string;
    status: 'open' | 'resolved' | 'overridden' | 'dismissed';
    blocking: boolean;
    simulated: boolean;
    createdAt: string;
    updatedAt?: string;
}

export interface GuardianEvent {
    tenantId: string;
    eventType: string; // e.g., 'data_share', 'ai_generate', 'export', 'message_send'
    subjectType: 'student' | 'case' | 'report' | 'message';
    subjectId: string;
    context: Record<string, any>; // Flexible context (content, destination, etc.)
    actorId: string;
    timestamp: string;
}

export interface PolicyRule {
    id: string;
    tenantId: string;
    name: string;
    description: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    
    triggerEvent: string; // matches GuardianEvent.eventType
    triggerCondition: 'regex' | 'keyword' | 'missing_consent' | 'missing_metadata' | 'pii_leak' | 'safeguarding_recommended';
    
    // Configuration
    keywords?: string[];
    regexPattern?: string;
    requiredConsentCategory?: string;
    
    // Actions
    mode: 'enforce' | 'monitor'; // Enforce = block, Monitor = log only
    rolloutMode?: 'simulate' | 'live';
    blockActions: boolean;
    remediation?: string;
    
    enabled: boolean;
    status: 'active' | 'deprecated';
}

export interface GuardianOverrideRequest {
    id: string;
    tenantId: string;
    ruleIds: string[];
    subjectId: string;
    requestedBy: string;
    reason: string;
    status: 'pending' | 'approved' | 'rejected';
    approvedBy?: string;
    approvedAt?: string;
}

// --- Sprint 4: Appointments & Calendar ---

export interface AvailabilitySlot {
    id: string; // "monday-0900-1200"
    tenantId: string;
    userId: string; // EPP ID
    dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0 = Sunday
    startTime: string; // "09:00"
    endTime: string; // "17:00"
    isException?: boolean; // If true, specific date overrides weekly pattern
    exceptionDate?: string; // ISO Date "2023-10-25"
    bufferMinutes: number; // e.g. 15
}

export interface Appointment {
    id: string;
    tenantId: string;
    hostUserId: string; // EPP
    participantIds: string[]; // Parents, Staff
    studentId?: string;
    
    title: string;
    description?: string;
    
    startAt: string; // ISO Timestamp
    endAt: string; // ISO Timestamp
    timeZone: string; // "Europe/London"
    
    status: 'scheduled' | 'cancelled' | 'completed' | 'no_show';
    type: 'consultation' | 'telehealth' | 'assessment' | 'follow_up';
    
    // Telehealth & Integrations
    locationType: 'in_person' | 'video' | 'phone';
    meetingLink?: string; // Zoom/Jitsi URL
    meetingPassword?: string;
    
    // Consent & Privacy
    recordingConsent?: boolean; // Has parent consented to recording?
    consentProofId?: string; // Link to ConsentRecord
    
    // Sync
    externalEventId?: string; // Google Calendar ID
    syncStatus?: 'synced' | 'failed' | 'pending';
    
    remindersSent: boolean;
    
    createdAt: string;
    createdBy: string;
}

export interface CalendarIntegration {
    userId: string;
    provider: 'google' | 'outlook';
    accessToken: string; // Encrypted at rest
    refreshToken: string; // Encrypted at rest
    expiresAt: number;
    syncEnabled: boolean;
    calendarId?: string; // Target calendar ID
}

// --- Sprint 5: Internal Messaging (Secure Chat) ---

export interface ChatChannel {
    id: string;
    tenantId: string;
    type: 'direct' | 'group' | 'case';
    participantIds: string[];
    name?: string; // For groups
    caseId?: string; // Link to specific case
    lastMessage?: {
        text: string;
        senderId: string;
        sentAt: string;
    };
    metadata?: Record<string, any>;
    createdAt: string;
    updatedAt: string;
}

export interface ChatMessage {
    id: string;
    chatId: string;
    senderId: string;
    content: string; // Text
    type: 'text' | 'image' | 'voice' | 'file' | 'system';
    
    attachments?: {
        id: string;
        url: string; // Secure signed URL
        type: string;
        name: string;
    }[];
    
    // Status
    readBy: string[]; // User IDs
    deliveredTo: string[];
    
    // Safety
    flagged?: boolean;
    flagReason?: string;
    
    createdAt: string;
    replyToId?: string;
}

// --- Sprint 6: AI Chatbot (Copilot) ---

export interface BotSession {
    id: string;
    tenantId: string;
    userId: string;
    mode: 'copilot' | 'parent_help';
    context?: {
        studentId?: string;
        caseId?: string;
        pageUrl?: string;
    };
    createdAt: string;
    updatedAt: string;
}

export interface BotMessage {
    id: string;
    sessionId: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    
    // RAG Metadata
    citations?: {
        sourceId: string; // Doc ID or Web URL
        text: string;
        relevance: number;
    }[];
    
    confidence?: number;
    
    // Provenance
    provenanceId?: string; // Link to ai_provenance log
    
    createdAt: string;
}

// --- Country OS: Knowledge Documents & Policy Drafts ---

export interface KnowledgeDocument {
    id: string;
    type: 'rulebook' | 'report' | 'evidence';
    title: string;
    ownerId: string;
    tenantId?: string; // If null, global/system doc
    visibility: 'private' | 'team' | 'public';
    storagePath: string; // GS path
    
    status: 'uploaded' | 'processing' | 'indexed' | 'error';
    
    metadata: {
        originalFileName: string;
        authority?: string; // For rulebooks
        evidenceType?: string; // For evidence
        publicationYear?: string;
        trustScore?: number;
        verified?: boolean;
        caseTags?: string[];
    };
    
    createdAt: string;
}

export interface PolicyRuleDraft {
    id: string;
    tenantId: string;
    sourceDocumentId: string;
    
    extractedText: string;
    citations: string[]; // Chunk IDs
    
    confidence: number; // AI confidence 0-1
    status: 'draft' | 'approved' | 'rejected';
    
    structuredDraft: {
        title: string;
        severity: 'low' | 'medium' | 'high' | 'critical';
        triggerCondition: string;
        remediation: string;
        mode: 'advisory' | 'enforce';
        blockActions: boolean;
    };
    
    createdAt: string;
    reviewedBy?: string;
    reviewedAt?: string;
}

// PHASE 14: Professional Verification (HCPC)
export interface VerificationRecord {
    hcpcNumber?: string; // e.g. "PYL043132"
    status: 'unverified' | 'pending' | 'verified' | 'rejected';
    verifiedAt?: string;
    verifiedBy?: string; // Admin User ID
    verificationNote?: string;
    documents?: { url: string; name: string }[];
}

// Update UserProfile or create StaffProfile interface extension
export interface StaffProfile {
    id: string; // userId
    tenantId: string;
    role: string;
    firstName: string;
    lastName: string;
    email: string;
    
    // Phase 14: Trust Engine
    verification?: VerificationRecord;
    
    // Country OS Extensions (SCR)
    extensions?: Record<string, any>;
}

export interface MarketplaceItem {
    id: string;
    type: 'pack' | 'template' | 'workflow';
    title: string;
    description: string;
    version: string;
    publisherId: string;
    publisherOrg: string;
    regionTags: string[]; // e.g. 'UK', 'US', 'Global'
    categories: string[]; // e.g. 'Compliance', 'Assessment'
    
    licensing: {
        licenseType: 'free' | 'per_seat' | 'site_license';
        price?: { amount: number; currency: string };
    };
    
    installManifest: any; // The JSON blob
    certified: boolean; // MindKindler Verified
    
    stats: {
        installs: number;
        rating: number;
    };
    
    createdAt: string;
    updatedAt: string;
}

export interface MarketplaceReview {
    id: string;
    itemId: string;
    userId: string;
    rating: number; // 1-5
    comment?: string;
    createdAt: string;
}

export interface InstalledPack {
    id: string;
    tenantId: string;
    packId: string;
    version: string;
    status: 'installed' | 'updating' | 'error';
    installedAt: string;
    installedBy: string;
    configSnapshot?: any;
}
