// src/types/schema.ts

// ... (Role & Other Interfaces remain same)
export type Role = 
    'SuperAdmin' | 
    'TenantAdmin' | 
    'EPP' | 
    'EducationalPsychologist' | 
    'Assistant' | 
    'TrustedAssistant' | 
    'SchoolAdmin' | 
    'ParentUser' | 
    'GovAnalyst';

// --- Phase 43: Safeguarding & Risk Escalation ---

export type RiskSeverity = 'low' | 'moderate' | 'high' | 'immediate_danger';
export type EscalationChannel = 'email_only' | 'call_and_email' | 'call_only';

export interface SafeguardingEvent {
  id: string;
  studentId: string;
  caseId: string;
  consultationId?: string; // If triggered during a session
  reportedBy: string; // EPP ID
  timestamp: string;
  severity: RiskSeverity;
  category: 'self_harm' | 'suicide_risk' | 'abuse' | 'neglect' | 'other';
  description: string;
  
  // Who was contacted?
  actionsTaken: {
    contactId: string;
    role: 'SENCO' | 'Parent' | 'Safeguarding_Lead' | 'Social_Services';
    channel: EscalationChannel;
    status: 'sent' | 'failed' | 'logged_manually';
    emailContent?: string; // Evidence
    timestamp: string;
  }[];
}

// Extended Contact Interface for scalable emergency contacts
export interface StudentContact {
  id: string;
  name: string;
  relationship: string; // e.g. "Mother", "SENCO"
  email: string;
  phone: string;
  isEmergencyContact: boolean;
  hasParentalResponsibility: boolean;
}

// --- Phase 37: Enterprise & White Labeling ---

export interface TenantBranding {
    logoUrl?: string; // e.g. "https://storage.../leeds-logo.png"
    primaryColor?: string; // Hex e.g. "#4f46e5"
    headerText?: string; // e.g. "Leeds City Council - SEND Services"
    footerText?: string; // e.g. "Official Sensitive - Not for distribution"
    reportTemplateId?: string; // Default docx template
}

export interface TenantConfig {
    id: string;
    name: string;
    region: string;
    plan: 'free' | 'pro' | 'enterprise';
    
    branding?: TenantBranding;
    
    // Limits
    usage: {
        maxReportsPerMonth: number;
        currentReportsMonth: number;
        resetAt: string;
    };
    
    features: {
        allowAi: boolean;
        allowCopilot: boolean;
        allowWhiteLabel: boolean;
    };
}

// ... (Rest of existing interfaces: Certification, TrainingModule, etc.)
export interface Certification {
    id: string;
    userId: string;
    tenantId: string;
    name: string; 
    issuer: string; 
    referenceNumber?: string;
    expiryDate?: string; 
    status: 'active' | 'expiring' | 'expired' | 'revoked';
    proofUrl?: string; 
    verifiedAt?: string;
    verifiedBy?: string;
}

export interface TrainingQuizQuestion {
    id: string;
    text: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
}

export interface TrainingLesson {
    id: string;
    title: string;
    type: 'video' | 'text' | 'quiz';
    contentUrl?: string; 
    textContent?: string; 
    questions?: TrainingQuizQuestion[]; 
    durationMinutes: number;
    completed?: boolean;
}

export interface TrainingModule {
    id: string;
    tenantId: string;
    assignedUserId: string;
    title: string;
    description?: string;
    generatedBy: 'system' | 'ai_gap_scanner' | 'supervisor';
    rationale?: string; 
    content: TrainingLesson[];
    status: 'pending' | 'in_progress' | 'completed';
    progressPercent: number;
    dueDate?: string;
    completedAt?: string;
    linkedAuditEvents?: string[]; 
}

export interface ExamResult {
    id: string;
    moduleId: string;
    userId: string;
    score: number; 
    pass: boolean;
    certificateUrl?: string; 
    attemptDate: string;
}

export interface ProvenanceMetadata {
    source: 'manual' | 'ocr' | 'lms' | 'parent_portal' | 'migration';
    sourceId?: string;
    confidence?: number;
    verified: boolean;
    verifiedBy?: string;
    verifiedAt?: string;
    autoGenerated?: boolean;
}

export type ProvenanceField<T> = {
    value: T;
    metadata: ProvenanceMetadata;
}

export interface VerificationTask {
    id: string;
    studentId: string;
    fieldPath: string;
    description: string;
    status: 'pending' | 'verified' | 'rejected' | 'skipped';
    assignedTo?: string;
    dueDate?: string;
    evidenceRef?: string;
    createdAt: string;
    resolvedAt?: string;
    resolvedBy?: string;
}

export interface ParentRecord {
    id: string;
    tenantId: string;
    firstName: string;
    lastName: string;
    relationshipType: 'Mother' | 'Father' | 'Guardian' | 'Foster Carer' | 'Step-Parent' | 'Grandparent' | 'Other';
    email?: string;
    phone?: string;
    address?: string;
    hasParentalResponsibility: boolean;
    isPrimaryContact: boolean;
    isEmergencyContact: boolean;
    canPickUp: boolean;
    occupation?: string;
    employer?: string;
    languages: string[];
    communicationPreferences?: {
        email: boolean;
        sms: boolean;
        phone: boolean;
        preferredTime?: string;
    };
    verificationStatus: 'unverified' | 'verified_id' | 'verified_in_person';
    metadata?: ProvenanceMetadata;
}

export interface FosterPlacement {
    id: string;
    carerName: string;
    agencyName: string;
    startDate: string;
    endDate?: string;
    reasonForMove?: string;
    legalStatus: string;
    socialWorkerName?: string;
    contactInfo?: string;
    metadata: ProvenanceMetadata;
}

export interface DisciplineIncident {
    id: string;
    date: string;
    type: string;
    description: string;
    outcome: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    involvedParties?: string[];
    reportedBy: string;
    isPoliceInvolved?: boolean;
    isSafeguarding?: boolean;
    metadata: ProvenanceMetadata;
}

export interface HealthRecord {
    gpName?: string;
    gpPractice?: string;
    nhsNumber?: string;
    allergies: ProvenanceField<string[]>;
    conditions: ProvenanceField<string[]>;
    medications: ProvenanceField<string[]>;
    immunizations?: ProvenanceField<string[]>;
    dietaryNeeds?: string;
    emergencyPlan?: string;
}

export interface ConsentRecord {
    id: string;
    studentId: string;
    parentId?: string;
    category: 'education_share' | 'health_share' | 'media_recording' | 'research' | 'marketing' | 'third_party';
    status: 'granted' | 'denied' | 'revoked' | 'expired';
    grantedAt: string;
    expiresAt?: string;
    evidenceFileId?: string;
    notes?: string;
}

export type AcademicSubject = 'Math' | 'English' | 'Science' | 'History' | 'Geography' | 'Art' | 'PE' | 'Music' | 'Other';
export type GradeType = 'Term' | 'Exam' | 'Predicted' | 'Standardized';

export interface HistoricalAcademicRecord {
    id: string;
    studentId: string;
    academicYear: string;
    term: string;
    subject: AcademicSubject;
    grade: string | number;
    maxGrade?: number;
    type: GradeType;
    source: string;
    date: string;
    metadata: ProvenanceMetadata;
}

export interface HistoricalAttendanceSummary {
    id: string;
    studentId: string;
    academicYear: string;
    term: string;
    totalDays: number;
    daysPresent: number;
    daysAbsent: number;
    daysLate: number;
    unauthorizedAbsences: number;
    attendancePercentage: number;
    source: string;
    metadata: ProvenanceMetadata;
}

export interface StudentHistory {
    academic: HistoricalAcademicRecord[];
    attendance: HistoricalAttendanceSummary[];
    behavior: DisciplineIncident[]; 
}

export interface StudentRecord {
    id: string;
    tenantId: string;
    schoolId?: string; 
    identity: {
        firstName: ProvenanceField<string>;
        lastName: ProvenanceField<string>;
        middleName?: ProvenanceField<string>;
        preferredName?: string;
        dateOfBirth: ProvenanceField<string>;
        gender: ProvenanceField<string>;
        nationalId?: ProvenanceField<string>;
        upi?: ProvenanceField<string>;
        photoUrl?: string;
    };
    education: {
        currentSchoolId?: ProvenanceField<string>;
        enrollmentDate?: ProvenanceField<string>;
        yearGroup?: ProvenanceField<string>;
        formGroup?: string;
        senStatus?: ProvenanceField<string>;
        fsmStatus?: ProvenanceField<boolean>;
        ealStatus?: ProvenanceField<boolean>;
        attendancePercentage?: ProvenanceField<number>;
    };
    family: {
        parents: ParentRecord[];
        siblings?: { name: string; dob?: string; school?: string }[];
        languageHome?: string;
    };
    health: HealthRecord;
    careHistory?: {
        isLookedAfter: boolean;
        socialWorker?: { name: string; email: string; phone: string };
        placements: FosterPlacement[];
    };
    discipline?: DisciplineIncident[];
    timeline?: StudentHistory;
    extensions?: Record<string, any>; 
    meta: {
        createdAt: string;
        createdBy: string;
        updatedAt: string;
        updatedBy: string;
        trustScore: number;
        completenessScore: number;
        privacyLevel: 'standard' | 'high' | 'restricted';
    };
}

export interface AiFeedback {
    id: string;
    tenantId: string;
    userId: string;
    traceId: string;
    feature: string;
    rating: 'positive' | 'negative';
    reason?: 'hallucination' | 'style' | 'missed_fact' | 'unsafe' | 'other';
    comment?: string;
    correctedValue?: string;
    createdAt: string;
}

export interface AssessmentRecommendation {
    templateId: string;
    title: string;
    category: string;
    reasoning: string;
    confidence: 'high' | 'medium' | 'low';
    isAvailable: boolean;
}

export interface Notification {
  id: string;
  tenantId: string;
  recipientUserId: string;
  type: 'info' | 'success' | 'warning' | 'error' | 'action_required';
  category: 'assessment' | 'training' | 'guardian' | 'partner' | 'system';
  title: string;
  message: string;
  link?: string;
  read: boolean;
  createdAt: string;
  metadata?: Record<string, any>;
}

export interface NotificationPreferences {
  userId: string;
  channels: { email: boolean; sms: boolean; push: boolean };
  categories: {
    assessment: boolean;
    training: boolean;
    guardian: boolean;
    partner: boolean;
    system: boolean;
  };
}

export interface UploadedDocument {
  id: string;
  tenantId: string;
  fileName: string;
  status: 'processing' | 'review_required' | 'processed';
  uploadedAt: string;
  uploadedBy: string;
  url: string;
}

export interface AssessmentTemplate {
  id: string;
  tenantId: string;
  title: string;
  description: string;
  category?: string;
  questions: any[];
  createdAt: string;
  updatedAt: string;
  status: 'draft' | 'published';
  tags: string[];
}

export interface AssessmentAssignment {
  id: string;
  tenantId: string;
  templateId: string;
  studentId?: string;
  targetId?: string;
  assignedByUserId: string;
  assignedAt: string;
  dueDate?: string;
  mode?: 'student-async' | 'clinician-live';
  status: 'pending' | 'in_progress' | 'completed' | 'graded';
  responses?: Record<string, any>;
  grade?: number;
  feedback?: string;
}

export interface TenantLocalizationSettings {
  defaultLocale: string;
  supportedLocales: string[];
  allowUserLocaleOverride: boolean;
  updatedAt: string;
  updatedBy: string;
  publishedBy?: string;
}

export interface TenantSettings {
  localization?: TenantLocalizationSettings;
}

export interface TranslationOverrideDoc {
  id?: string;
  locale: string;
  namespace: string;
  entries: Record<string, string>;
  status: 'draft' | 'published';
  updatedAt: string;
  updatedBy: string;
  publishedAt?: string;
  publishedBy?: string;
}

export interface GlossaryDoc {
  id?: string;
  locale: string;
  entries: Record<string, string>;
  status: 'draft' | 'published';
  updatedAt: string;
  updatedBy: string;
  publishedAt?: string;
  publishedBy?: string;
}

export interface ConsultationSession {
  id: string;
  tenantId: string;
  studentId: string;
  date: string;
  notes: string;
  mode: 'person_centered' | 'multi_agency' | 'complex' | 'standard';
  participants: string[];
  audio_url?: string;
  transcript?: {
    startTime: number;
    endTime: number;
    speaker: string;
    text: string;
  }[];
  ai_insights?: {
    timestamp: number;
    text: string;
    type: string;
  }[];
  clinical_observations?: {
    timestamp: number;
    text: string;
  }[];
  linked_assessment_id?: string;
  accessibility?: {
    visual_aids: boolean;
    sign_language_record: boolean;
    live_captions: boolean;
  };
  participant_device_id?: string;
  status?: 'scheduled' | 'in_progress' | 'completed' | 'synthesized' | 'cancelled';
  type?: string; 
  reportId?: string;
  caseId?: string;
}

export interface ConsultationEvent {
  timestamp: string; 
  speaker: 'epp' | 'student';
  type: 'audio_transcript' | 'visual_card_selection' | 'ai_insight';
  data?: any; 
}

export interface Student {
  id: string;
  tenantId: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender?: string;
  schoolId?: string;
  parentId?: string;
  address?: string;
  needs?: string[];
  alerts?: any[];
  diagnosisCategory?: string[];
  history?: string;
  consent?: {
      shareReports: boolean;
      shareDataForTraining: boolean;
      contactEmail?: string;
  };
}

export type CasePriority = 'Critical' | 'High' | 'Medium' | 'Low';
export type CaseStatus = 'triage' | 'active' | 'waiting' | 'resolved' | 'archived';

export interface Case {
  id: string;
  tenantId: string;
  type: 'student' | 'school' | 'staff';
  subjectId: string;
  title: string;
  description: string;
  status: CaseStatus;
  priority: CasePriority;
  assignedTo?: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  sourceAlertId?: string;
  evidence?: any[];
  tags?: string[];
  slaDueAt?: string;
  activities?: { 
      date: string;
      summary: string;
      performedBy: string;
      type?: string;
  }[];
}

export interface CaseTask {
  id?: string;
  tenantId: string; 
  caseId?: string;  
  studentId?: string; 
  title: string;
  description?: string;
  type: 'data_entry' | 'interview' | 'research' | 'observation' | 'report_drafting' | 'general'; 
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'pending' | 'in_progress' | 'review' | 'completed' | 'late';
  assignedTo: string; 
  assignedBy: string; 
  dueAt: string;
  attachments?: {
      name: string;
      url: string;
  }[];
  escalationPolicy?: {
      escalateAt: string; 
      escalateTo: string; 
  };
  createdAt: string;
  completedAt?: string;
}

export interface CaseTimelineEvent {
  id?: string;
  type: 'status_change' | 'note' | 'document' | 'alert_linked' | 'task_completed' | 'assignment_change';
  content: string;
  metadata?: Record<string, any>;
  actorId: string;
  createdAt: string;
}

export interface AssessmentResult {
  id: string;
  studentId: string;
  templateId: string;
  totalScore: number;
  maxScore: number;
  completedAt?: string;
  startedAt?: string;
  category?: string;
  grade?: string;
  responses?: Record<string, any>;
  status?: 'pending' | 'in_progress' | 'completed' | 'graded';
  aiAnalysis?: string;
}

export interface ExternalAcademicRecord {
  id: string;
  studentId: string;
  subject: string;
  grade: string | number;
  term: string;
  date: string;
  sourceSystem: string;
}

export interface AttendanceRecord {
  id: string;
  studentId: string;
  date: string;
  status: 'present' | 'absent' | 'late' | 'excused';
  notes?: string;
}

export interface InterventionPlan {
  id: string;
  tenantId: string;
  studentId: string;
  title: string;
  status: 'active' | 'completed' | 'draft' | 'archived';
  startDate: string;
  endDate?: string;
  goalDescription: string;
  recommendations: Array<{
    title: string;
    description: string;
    assignedTo: string;
    steps?: string[];
    status: 'pending' | 'in_progress' | 'completed';
  }>;
  progressLogs?: Array<{
    at: string;
    note: string;
    progressDelta?: string;
    loggedBy: string;
  }>;
  createdAt: string;
  updatedAt: string;
  baselineScore?: number;
  targetScore?: number;
  currentScore?: number;
}

export interface RecommendationTemplate {
    id: string;
    category: string;
    title: string;
    description: string;
    impactScore: number;
    tags: string[];
}

export type RedactionLevel = 'FULL' | 'PARENT_SAFE' | 'ANONYMIZED';

export interface Citation {
    id: string;
    evidenceId: string;
    sourceType: string;
    label: string;
    trustScore?: number;
    snippet?: string;
    locationIndex?: number;
}

export interface ReportSection {
    id: string;
    title: string;
    content: string;
    lastAiGeneratedAt?: string;
    internalOnly?: boolean;
}

export interface ReportHistoryEvent {
    action: 'created' | 'edited' | 'submitted_review' | 'changes_requested' | 'approved' | 'signed';
    userId: string;
    timestamp: string;
    note?: string;
}

export interface Report {
    id: string;
    tenantId: string;
    studentId: string;
    caseId?: string;
    title: string;
    type: 'consultation' | 'statutory' | 'ehcp_review';
    templateType?: string;
    status: 'draft' | 'review' | 'signed' | 'archived' | 'pending_review' | 'changes_requested'; 
    version: number;
    content: {
        sections: ReportSection[];
    };
    citations?: Citation[];
    createdBy: string;
    createdAt: any;
    updatedAt: any;
    signedBy?: string;
    signedAt?: any;
    signatureHash?: string;
    locked?: boolean;
    aiProvenanceId?: string;
    supervisorId?: string; 
    history?: ReportHistoryEvent[]; 
}

export interface ReportVersion {
    id?: string;
    reportId: string;
    versionNumber: number;
    content: { sections: ReportSection[] };
    changeSummary?: string;
    committedBy: string;
    createdAt: any;
    type?: 'draft' | 'signed_final';
    signedBy?: string;
    signatureHash?: string;
}

export interface ReportShare {
    id: string;
    reportId: string;
    sharedWithEmail?: string;
    sharedWithUserId?: string;
    redactionLevel: RedactionLevel;
    permissions: 'view' | 'comment' | 'download';
    expiresAt?: string;
    createdAt: string;
    createdBy: string;
    accessKey?: string;
}

export interface ReportExport {
    id: string;
    reportId: string;
    versionId?: string;
    path: string;
    redactionLevel: RedactionLevel;
    requestedBy: string;
    createdAt: any;
}

export interface GuardianFinding {
    id: string;
    tenantId: string;
    ruleId: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    eventType: string;
    subjectType: string;
    subjectId: string;
    message: string;
    remediation?: string;
    status: 'open' | 'resolved' | 'overridden' | 'dismissed';
    blocking: boolean;
    simulated: boolean;
    createdAt: string;
    updatedAt?: string;
}

export interface GuardianEvent {
    tenantId: string;
    eventType: string; 
    subjectType: 'student' | 'case' | 'report' | 'message';
    subjectId: string;
    context: Record<string, any>; 
    actorId: string;
    timestamp: string;
}

export interface PolicyRule {
    id: string;
    tenantId: string;
    name: string;
    description: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    triggerEvent: string; 
    triggerCondition: 'regex' | 'keyword' | 'missing_consent' | 'missing_metadata' | 'pii_leak' | 'safeguarding_recommended';
    keywords?: string[];
    regexPattern?: string;
    requiredConsentCategory?: string;
    mode: 'enforce' | 'monitor'; 
    rolloutMode?: 'simulate' | 'live';
    blockActions: boolean;
    remediation?: string;
    enabled: boolean;
    status: 'active' | 'deprecated';
}

export interface GuardianOverrideRequest {
    id: string;
    tenantId: string;
    ruleIds: string[];
    subjectId: string;
    requestedBy: string;
    reason: string;
    status: 'pending' | 'approved' | 'rejected';
    approvedBy?: string;
    approvedAt?: string;
}

export interface AvailabilitySlot {
    id: string; 
    tenantId: string;
    userId: string; 
    dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6; 
    startTime: string; 
    endTime: string; 
    isException?: boolean; 
    exceptionDate?: string; 
    bufferMinutes: number; 
}

export interface Appointment {
    id: string;
    tenantId: string;
    hostUserId: string; 
    participantIds: string[]; 
    studentId?: string;
    title: string;
    description?: string;
    startAt: string; 
    endAt: string; 
    timeZone: string; 
    status: 'scheduled' | 'cancelled' | 'completed' | 'no_show';
    type: 'consultation' | 'telehealth' | 'assessment' | 'follow_up';
    locationType: 'in_person' | 'video' | 'phone';
    meetingLink?: string; 
    meetingPassword?: string;
    recordingConsent?: boolean; 
    consentProofId?: string; 
    externalEventId?: string; 
    syncStatus?: 'synced' | 'failed' | 'pending';
    remindersSent: boolean;
    createdAt: string;
    createdBy: string;
}

export interface CalendarIntegration {
    userId: string;
    provider: 'google' | 'outlook';
    accessToken: string; 
    refreshToken: string; 
    expiresAt: number;
    syncEnabled: boolean;
    calendarId?: string; 
}

export interface ChatChannel {
    id: string;
    tenantId: string;
    type: 'direct' | 'group' | 'case';
    participantIds: string[];
    name?: string; 
    caseId?: string; 
    lastMessage?: {
        text: string;
        senderId: string;
        sentAt: string;
    };
    metadata?: Record<string, any>;
    createdAt: string;
    updatedAt: string;
}

export interface ChatMessage {
    id: string;
    chatId: string;
    senderId: string;
    content: string; 
    type: 'text' | 'image' | 'voice' | 'file' | 'system';
    attachments?: {
        id: string;
        url: string; 
        type: string;
        name: string;
    }[];
    readBy: string[]; 
    deliveredTo: string[];
    flagged?: boolean;
    flagReason?: string;
    createdAt: string;
    replyToId?: string;
}

export interface BotSession {
    id: string;
    tenantId: string;
    userId: string;
    mode: 'copilot' | 'parent_help';
    context?: {
        studentId?: string;
        caseId?: string;
        pageUrl?: string;
    };
    createdAt: string;
    updatedAt: string;
}

export interface BotMessage {
    id: string;
    sessionId: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    citations?: {
        sourceId: string; 
        text: string;
        relevance: number;
    }[];
    confidence?: number;
    provenanceId?: string; 
    createdAt: string;
}

export interface KnowledgeDocument {
    id: string;
    type: 'rulebook' | 'report' | 'evidence';
    title: string;
    description?: string; 
    ownerId: string;
    tenantId?: string; 
    visibility: 'private' | 'team' | 'public';
    storagePath: string; 
    status: 'uploaded' | 'processing' | 'indexed' | 'error';
    metadata: {
        originalFileName: string;
        authority?: string; 
        evidenceType?: string; 
        publicationYear?: string;
        trustScore?: number;
        verified?: boolean;
        caseTags?: string[];
    };
    notes?: { 
        id: string;
        content: string;
        authorId: string;
        createdAt: string;
    }[];
    createdAt: string;
}

export interface PolicyRuleDraft {
    id: string;
    tenantId: string;
    sourceDocumentId: string;
    extractedText: string;
    citations: string[]; 
    confidence: number; 
    status: 'draft' | 'approved' | 'rejected';
    structuredDraft: {
        title: string;
        severity: 'low' | 'medium' | 'high' | 'critical';
        triggerCondition: string;
        remediation: string;
        mode: 'advisory' | 'enforce';
        blockActions: boolean;
    };
    createdAt: string;
    reviewedBy?: string;
    reviewedAt?: string;
}

export interface VerificationRecord {
    hcpcNumber?: string; 
    status: 'unverified' | 'pending' | 'verified' | 'rejected';
    verifiedAt?: string;
    verifiedBy?: string; 
    verificationNote?: string;
    documents?: { url: string; name: string }[];
}

export interface StaffProfile {
    id: string; 
    tenantId: string;
    role: string;
    firstName: string;
    lastName: string;
    email: string;
    verification?: VerificationRecord;
    extensions?: Record<string, any>;
}

export interface MarketplaceItem {
    id: string;
    type: 'pack' | 'template' | 'workflow';
    title: string;
    description: string;
    version: string;
    publisherId: string;
    publisherOrg: string;
    regionTags: string[]; 
    categories: string[]; 
    licensing: {
        licenseType: 'free' | 'per_seat' | 'site_license';
        price?: { amount: number; currency: string };
    };
    installManifest: any; 
    certified: boolean; 
    stats: {
        installs: number;
        rating: number;
    };
    createdAt: string;
    updatedAt: string;
}

export interface MarketplaceReview {
    id: string;
    itemId: string;
    userId: string;
    rating: number; 
    comment?: string;
    createdAt: string;
}

export interface InstalledPack {
    id: string;
    tenantId: string;
    packId: string;
    version: string;
    status: 'installed' | 'updating' | 'error' | 'active'; 
    installedAt: string;
    installedBy: string;
    configSnapshot?: any;
}

// --- Phase 40: External Portal & Magic Links ---

export type ContributionType = 'parent_view' | 'school_advice';
export type ContributionStatus = 'sent' | 'opened' | 'submitted' | 'expired';
export type ExternalRequestType = 'parent_view' | 'school_advice' | 'consent_request';
export type RequestStatus = 'sent' | 'opened' | 'submitted' | 'expired';

// The secure token object stored in DB
export interface ContributionRequest {
  id: string;
  tenantId: string;
  studentId: string;
  studentName: string; 
  recipientEmail: string;
  recipientRole: 'Parent' | 'SENCO' | 'Teacher';
  type: ContributionType;
  token: string; // Cryptographically secure string
  expiresAt: string; // ISO Date
  status: ContributionStatus;
  createdAt: string;
  createdBy: string; // EPP ID
}

// The actual data submitted back
export interface ContributionSubmission {
  id: string;
  requestId: string;
  studentId: string;
  submittedAt: string;
  
  // Structured data based on UK SEND Section A (Parent) or Section B (School)
  data: {
    // Common fields
    respondentName: string;
    
    // Parent Specific (Section A)
    childStrengths?: string[];
    childAspirations?: string;
    historyOfNeeds?: string;
    homeSupport?: string;
    
    // School Specific (Section B & F)
    currentAttainment?: Record<string, any>; // Math, English scores
    interventionsTried?: {
      name: string;
      duration: string;
      outcome: string;
    }[];
    attendance?: number;
  };
}

export interface ExternalRequest {
  id: string;
  tenantId: string;
  studentId: string;
  caseId: string;
  recipientEmail: string;
  recipientRole: 'Parent' | 'SENCO' | 'Teacher' | 'Student_16_Plus';
  type: ExternalRequestType;
  token: string; // 32-byte secure hex
  expiresAt: string; // 7 days
  status: RequestStatus;
  
  // For Consent Requests specifically
  consentConfig?: {
     requiresInvolvement: boolean; // Standard EP involvement
     requiresInformationSharing: boolean; // Multi-agency sharing
     requiresAudioRecording: boolean; // For AI Transcription
  };

  auditLog: {
    sentAt: string;
    openedAt?: string;
    ipAddress?: string;
    userAgent?: string;
  };
}

// The Submission Object (stored in 'contributions' collection)
export interface ExternalSubmission {
  id: string;
  requestId: string;
  studentId: string;
  submittedAt: string;
  signedBy: string; // Typed name
  data: any; // The form payload
}

// --- Phase 42: Telemetry & Gap Scanner ---

export interface ReportTelemetry {
   reportId: string;
   tenantId: string;
   sectionId: string; 
   aiVersion: string; // Original AI draft
   finalVersion: string; // EPP signed text
   editDistance: number; // Levenshtein or % difference
   timestamp: string;
   userId: string;
}
