// functions/src/reports/exportReport.ts
import { CallableRequest, onCall } from "firebase-functions/v2/https";
import * as admin from 'firebase-admin';
import * as puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

// Ensure admin initialized
if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore();
const storage = admin.storage();

export const exportReport = onCall({ 
    region: 'europe-west3',
    memory: '1GiB', // Increased memory for Puppeteer
    timeoutSeconds: 300,
    cors: true 
}, async (request: CallableRequest<any>) => {
    if (!request.auth) throw new Error('unauthenticated');

    const { tenantId, reportId, redactionLevel, format } = request.data;
    
    // 1. Fetch Report
    const reportSnap = await db.doc(`reports/${reportId}`).get(); 
    if (!reportSnap.exists) throw new Error('Report not found');
    
    const reportData = reportSnap.data();
    
    // 2. Apply Redaction
    const sections = reportData?.content?.sections || [];
    const visibleSections = redactionLevel === 'parent' 
        ? sections.filter((s: any) => !s.internalOnly)
        : sections;

    // 3. Generate HTML Content
    const brandingHtml = `
        <div style="text-align: right; margin-bottom: 20px;">
            <h1 style="color: #4f46e5; margin: 0;">MindKindler</h1>
            <p style="margin: 0; font-size: 12px; color: #666;">Clinical Report</p>
        </div>
    `;

    const reportHtml = `
        <html>
            <head>
                <style>
                    body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12pt; line-height: 1.5; color: #333; margin: 40px; }
                    h1 { font-size: 24pt; margin-bottom: 10px; }
                    h2 { font-size: 18pt; margin-top: 20px; border-bottom: 2px solid #eee; padding-bottom: 5px; }
                    h3 { font-size: 14pt; margin-top: 15px; color: #555; }
                    p { margin-bottom: 10px; }
                    .meta { background: #f9fafb; padding: 15px; border-radius: 8px; margin-bottom: 30px; }
                    .meta p { margin: 5px 0; }
                    .footer { font-size: 10px; text-align: center; color: #999; margin-top: 50px; border-top: 1px solid #eee; padding-top: 10px; }
                </style>
            </head>
            <body>
                ${brandingHtml}
                
                <h1>${reportData?.title || 'Clinical Report'}</h1>
                
                <div class="meta">
                    <p><strong>Student ID:</strong> ${reportData?.studentId || 'N/A'}</p>
                    <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
                    <p><strong>Redaction Level:</strong> ${redactionLevel}</p>
                </div>

                ${visibleSections.map((s: any) => `
                    <div class="section">
                        <h2>${s.title}</h2>
                        <div class="content">${s.content}</div>
                    </div>
                `).join('')}

                <div class="footer">
                    Generated by MindKindler OS • Confidential • ${new Date().getFullYear()}
                </div>
            </body>
        </html>
    `;

    // 4. Generate PDF via Puppeteer
    let browser = null;
    let pdfBuffer: Buffer;

    try {
        browser = await puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath(),
            headless: chromium.headless,
        });

        const page = await browser.newPage();
        await page.setContent(reportHtml, { waitUntil: 'networkidle0' });
        
        pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' }
        });

    } catch (error) {
        console.error("Puppeteer PDF generation failed:", error);
        throw new Error("PDF generation failed");
    } finally {
        if (browser) await browser.close();
    }
    
    // 5. Upload to Storage
    const bucket = storage.bucket();
    // Ensure unique path with timestamp
    const filePath = `exports/${tenantId}/${reportId}/${Date.now()}_${redactionLevel}.pdf`;
    const file = bucket.file(filePath);
    
    await file.save(pdfBuffer, {
        metadata: { contentType: 'application/pdf' }
    });

    // 6. Generate Signed URL
    const [url] = await file.getSignedUrl({
        action: 'read',
        expires: Date.now() + 60 * 60 * 1000 // 1 hour
    });

    // 7. Log Export
    await db.collection(`reports_exports`).add({
        tenantId,
        reportId,
        requestedBy: request.auth.uid,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        path: filePath,
        redactionLevel,
        format: 'pdf' // Hardcoded since we only support PDF here for now
    });

    return { downloadUrl: url, exportId: filePath };
});
