// src/app/actions/safeguarding.ts
"use server";

import * as admin from 'firebase-admin';
import { getFirestore } from "firebase-admin/firestore";
import { EscalationChannel, SafeguardingEvent, StudentRecord } from "@/types/schema";

// Ensure Admin Init
if (!admin.apps.length) {
    admin.initializeApp({ projectId: "mindkindler-84fcf" });
}

export interface EscalateRiskParams {
    studentId: string;
    contactIds: string[];
    method: 'email' | 'call_log';
    notes: string;
    detectedRisks: string[];
    tenantId?: string; // Optional if we infer
    userId?: string; // Optional if we infer
}

export async function escalateRisk(params: EscalateRiskParams) {
    console.log("ESCALATING RISK:", params);

    // 1. Resolve Context (User/Tenant)
    // In a real app, we'd use `headers()` or `cookies()` to verify session via Admin Auth
    // For this pilot action, we assume the caller is authorized or we'd check tokens.
    // For simplicity here, we assume the `studentId` allows us to find the tenant.
    
    // We need to find the student to get the tenant ID if not passed
    // We'll search in default DB or try a known shard if we knew it. 
    // Best practice: The client should pass tenantId, or we use a global lookup.
    
    // Let's assume we are in 'uk' region or default for now, or search.
    const db = admin.firestore(); // Default DB (Global)
    
    // Note: Student data is in Regional Shards. 
    // We'll try 'mindkindler-uk' first as primary pilot region.
    const region = 'uk';
    const shardId = `mindkindler-${region}`;
    const regionalDb = getFirestore(admin.app(), shardId);
    
    // Fetch Student & Contacts
    const studentRef = regionalDb.collection('students').doc(params.studentId);
    const studentSnap = await studentRef.get();
    
    if (!studentSnap.exists) {
        throw new Error("Student not found");
    }
    
    const studentData = studentSnap.data() as StudentRecord;
    const tenantId = studentData.tenantId;
    
    // 2. Resolve Selected Contacts
    // We need their emails/phone numbers from the student record
    const contactsToContact = studentData.family.parents.filter(p => params.contactIds.includes(p.id));
    
    // Also check for SENCO/School contacts if stored in 'education' or related collection
    // For MVP, we stick to parents found in 'family.parents'
    
    // 3. Create Safeguarding Event
    const eventRef = regionalDb.collection('safeguarding_events').doc();
    const event: SafeguardingEvent = {
        id: eventRef.id,
        studentId: params.studentId,
        caseId: 'generated-safeguarding', // Link to real case if available
        reportedBy: 'current-user-id', // TODO: Get from auth context
        timestamp: new Date().toISOString(),
        severity: 'high', // Inferred from "Escalation"
        category: 'other', // Could infer from detectedRisks
        description: params.notes,
        actionsTaken: contactsToContact.map(c => ({
            contactId: c.id,
            role: c.relationshipType as any,
            channel: params.method === 'email' ? 'email_only' : 'call_only',
            status: 'sent',
            timestamp: new Date().toISOString()
        }))
    };
    
    await eventRef.set(event);
    
    // 4. Send Emails (if method is email)
    if (params.method === 'email') {
        const mailBatch = regionalDb.batch();
        
        for (const contact of contactsToContact) {
            if (!contact.email) continue;
            
            const mailRef = regionalDb.collection('mail_queue').doc();
            mailBatch.set(mailRef, {
                to: contact.email,
                subject: `URGENT: Safeguarding Concern - ${studentData.identity.firstName.value} ${studentData.identity.lastName.value}`,
                html: `
                    <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e11d48; border-radius: 8px;">
                        <h2 style="color: #e11d48;">CONFIDENTIAL: Safeguarding Alert</h2>
                        <p>Dear ${contact.firstName},</p>
                        <p>An urgent safeguarding concern has been raised regarding <strong>${studentData.identity.firstName.value}</strong>.</p>
                        <p><strong>Clinical Note:</strong><br/>${params.notes}</p>
                        <p>Please contact the school or lead professional immediately.</p>
                        <hr/>
                        <p style="font-size: 12px; color: #666;">This message was generated by the MindKindler Safeguarding Protocol.</p>
                    </div>
                `,
                status: 'pending',
                createdAt: new Date().toISOString()
            });
        }
        await mailBatch.commit();
    }
    
    // 5. Notify System Admin (Audit)
    await regionalDb.collection('notifications').add({
        tenantId,
        recipientUserId: 'admin', // Placeholder for Tenant Admin
        type: 'error', // Use 'error' style for Critical alerts
        category: 'guardian',
        title: 'Safeguarding Escalation Triggered',
        message: `Risk escalated for student ${params.studentId}. ${contactsToContact.length} contacts notified.`,
        read: false,
        createdAt: new Date().toISOString()
    });

    return { success: true, eventId: event.id };
}
