import { CaseFile } from "../../types/case";
import { EvidenceItem } from "../../types/evidence";
import { generateEngagementPlan, EngagementPlan } from "../clinical/engagement-engine";
import { differenceInYears, parseISO } from "date-fns";

/**
 * Report generated by the Gap Scanner.
 */
export interface GapReport {
    /** List of specific documents/evidence types missing (e.g., "Hearing Check", "Social Care Report") */
    missingItems: string[];
    
    /** Are all CRITICAL statutory elements present? */
    isReadyForDrafting: boolean;
    
    /** Optional notes on why it's not ready (e.g. "Child is < 5 but missing Paediatrician report") */
    blockingReason?: string;
    
    /** The clinical plan that drove this analysis */
    clinicalPlan: EngagementPlan;
}

/**
 * The "Gap Scanner" Logic.
 * 
 * It bridges the "Clinical Ideal" (what the Engagement Engine wants) 
 * with the "Administrative Reality" (what files we actually have).
 * 
 * @param caseFile - The core case object (provides context like Age, Social Worker status).
 * @param currentEvidence - The array of files currently ingested and categorized.
 * @returns A GapReport detailing what is missing.
 */
export function calculateKnowledgeGaps(caseFile: CaseFile, currentEvidence: EvidenceItem[]): GapReport {
    
    // 1. Get the "Gold Standard" plan for this child
    const engagementContext = {
        dob: caseFile.dob,
        isNonVerbal: caseFile.flags.isNonVerbal,
        hasSocialWorker: caseFile.flags.hasSocialWorker
    };
    
    const clinicalPlan = generateEngagementPlan(engagementContext);
    const missingItems: string[] = [];
    
    // 2. Map Categorized Evidence to a "Set" for O(1) lookups
    const presentCategories = new Set(currentEvidence.map(e => e.category));
    
    // 3. Check Universal Statutory Requirements (Required for ALL EHCPs)
    
    // Requirement A: Parent Views (Section A)
    if (!presentCategories.has('parental_advice')) {
        missingItems.push("Parental Advice (Section A)");
    }
    
    // Requirement B: School Advice (Section B)
    // We check for general school reports or specific advice
    if (!presentCategories.has('school_report')) {
        missingItems.push("School/Setting Educational Advice");
    }

    // 4. Check Clinical Plan Requirements
    
    // If Clinical Plan demands "Social Care Statutory Advice" (because hasSocialWorker is true)
    if (clinicalPlan.requiredEvidence.includes('Social Care Statutory Advice')) {
        if (!presentCategories.has('social_care_report')) {
            missingItems.push("Social Care Statutory Advice (Looked After Child / CIN)");
        }
    }

    // 5. Check Age-Specific Statutory Nuances
    const age = differenceInYears(new Date(), parseISO(caseFile.dob));
    
    // Under 5s usually require a specific Community Pediatrician or Health Visitor report
    if (age < 5 && !presentCategories.has('medical_report')) {
        missingItems.push("Community Pediatrician / Health Visitor Report (Early Years)");
    }
    
    // 6. Check Sensory Requirements (Best Practice)
    // If not present, we often flag it as a "Soft Gap" (warning but not strictly blocking drafting if legally deadline is close)
    // For strictness in this version, we will flag it if completely absent.
    const hasHearing = currentEvidence.some(e => e.category === 'hearing_vision' || e.filename.toLowerCase().includes('hearing') || e.filename.toLowerCase().includes('audiology'));
    if (!hasHearing) {
        // We might not BLOCK drafting, but we list it.
        // missingItems.push("Hearing/Vision Check (Recommended)"); 
        // Commented out for now to avoid blocking on non-statutory items, but good for "Best Practice" mode.
    }

    // 7. Determine Readiness
    const isReadyForDrafting = missingItems.length === 0;

    return {
        missingItems,
        isReadyForDrafting,
        blockingReason: isReadyForDrafting ? undefined : `Missing ${missingItems.length} statutory evidence items.`,
        clinicalPlan
    };
}
